from app.utils.exception_utils import CustomException, handle_exception